spring.application.name=expense-splitter

spring.datasource.url=jdbc:postgresql://localhost:5433/expense_splitter
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=expense_splitter
spring.datasource.password=expense_splitter

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
